CREATE TABLE payments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id            BIGINT                         NOT NULL REFERENCES sales (id) ON DELETE RESTRICT,
    amount             NUMERIC(10, 2)                 NOT NULL,
    method             VARCHAR(26)                    NOT NULL,
    status             VARCHAR(26)                    NOT NULL DEFAULT 'POSTED',
    change             NUMERIC(10, 2)                 NOT NULL DEFAULT 0,
    paid_at            TIMESTAMP                      NOT NULL,
    reference          VARCHAR(100),
    created_by_user_id BIGINT                         NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE NULL
);

CREATE INDEX idx_payments_sale ON payments (sale_id);
CREATE INDEX idx_payments_paid_at ON payments (paid_at);

ALTER TABLE payments
    ADD CONSTRAINT chk_payments_amount_positive CHECK ( amount > 0 ),
    ADD CONSTRAINT chk_payments_change_nonnegative CHECK ( change >= 0 );
