CREATE TABLE public.users
(
    id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email         varchar(190)                   NOT NULL UNIQUE,
    password_hash varchar(255)                   NOT NULL,
    enabled       boolean                        NOT NULL,
    created_at    timestamp(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE public.user_roles
(
    user_id bigint       NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    role    varchar(255) NOT NULL,
    PRIMARY KEY (user_id, role)
)