CREATE TABLE IF NOT EXISTS public.users
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(190)                   NOT NULL UNIQUE,
    password_hash VARCHAR(255)                   NOT NULL,
    enabled       BOOLEAN                        NOT NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id BIGINT       NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    role    VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role)
)