CREATE TABLE IF NOT EXISTS inventory_movements
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deleted            BOOLEAN                        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    -- Tipo de movimiento (IN / OUT / ADJUST)
    movement_type      VARCHAR(20)                    NOT NULL,
    -- SALE / PURCHASE / RETURN / MANUAL / etc.
    source_type        VARCHAR(30)                    NOT NULL DEFAULT 'MANUAL',
    -- ID del documento de origen. Ej: sales.id si source_type='SALE'
    source_id          BIGINT,

    reason             VARCHAR(255),
    created_by         VARCHAR(255),
    created_by_user_id BIGINT                         REFERENCES users (id) ON DELETE SET NULL,

    -- Regla: si es MANUAL va sin source_id
    CONSTRAINT ck_inv_mov_source_id_required
        CHECK (
            (source_type = 'MANUAL' AND source_id IS NULL) OR
            (source_type <> 'MANUAL' AND source_id IS NOT NULL)
            )
);

CREATE INDEX IF NOT EXISTS idx_inv_mov_type_created_at ON inventory_movements (movement_type, created_at);
CREATE INDEX IF NOT EXISTS idx_inv_mov_created_at ON inventory_movements (created_at);
CREATE INDEX IF NOT EXISTS idx_inv_mov_source ON inventory_movements (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_inv_mov_created_by_user_id ON inventory_movements (created_by_user_id);

CREATE TABLE IF NOT EXISTS inventory_movement_items
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    movement_id    BIGINT  NOT NULL REFERENCES inventory_movements (id) ON DELETE CASCADE,
    product_id     BIGINT  NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    quantity       INTEGER NOT NULL CHECK ( quantity > 0 ),
    previous_stock INTEGER NOT NULL,
    new_stock      INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_inv_item_movement_id ON inventory_movement_items (movement_id);
CREATE INDEX IF NOT EXISTS idx_inv_item_product_id ON inventory_movement_items (product_id);
CREATE INDEX IF NOT EXISTS idx_inv_item_product_movement ON inventory_movement_items (product_id, movement_id);


ALTER TABLE inventory_movement_items
    ADD CONSTRAINT uq_inv_item_movement_product UNIQUE (movement_id, product_id);