CREATE TABLE IF NOT EXISTS suppliers
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(150)                   NOT NULL,
    document_number VARCHAR(30),
    phone           VARCHAR(30),
    email           VARCHAR(120),

    deleted         BOOLEAN                        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT uq_suppliers_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS purchases
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchase_date      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status             VARCHAR(20)                    NOT NULL DEFAULT 'DRAFT',   -- DRAFT/POSTED/VOIDED
    document_type      VARCHAR(20)                    NOT NULL DEFAULT 'INVOICE', -- INVOICE/RECEIPT/GUIDE/OTHER
    document_number    VARCHAR(60),

    supplier_id        BIGINT REFERENCES suppliers (id) ON DELETE RESTRICT,

    total_amount       NUMERIC(10, 2)                 NOT NULL DEFAULT 0,
    notes              VARCHAR(255),

    created_by_user_id BIGINT,

    posted_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    posted_by_user_id  BIGINT,

    voided_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    voided_by_user_id  BIGINT,
    void_reason        VARCHAR(255),

    created_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_purchases_date ON purchases (purchase_date);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier ON purchases (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchases_status ON purchases (status);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS perishable BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS purchase_items
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchase_id BIGINT         NOT NULL REFERENCES purchases (id) ON DELETE CASCADE,
    product_id  BIGINT         NOT NULL REFERENCES products (id) ON DELETE RESTRICT,

    quantity    INTEGER        NOT NULL CHECK ( quantity > 0 ),
    unit_cost   NUMERIC(10, 2) NOT NULL CHECK ( unit_cost >= 0 ),
    sub_total   NUMERIC(10, 2) NOT NULL CHECK ( sub_total >= 0 )
);

CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase ON purchase_items (purchase_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_product ON purchase_items (product_id);


CREATE TABLE IF NOT EXISTS product_batches
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id       BIGINT                         NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    purchase_item_id BIGINT                         REFERENCES purchase_items (id) ON DELETE SET NULL,

    batch_code       VARCHAR(80),
    received_at      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    expires_at       TIMESTAMP(6) WITHOUT TIME ZONE NULL,

    qty_initial      INTEGER                        NOT NULL CHECK ( qty_initial >= 0 ),
    qty_available    INTEGER                        NOT NULL CHECK ( qty_available >= 0 ),

    unit_cost        NUMERIC(10, 2)                 NULL,

    created_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_batches_product_expires ON product_batches (product_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_batches_product_received ON product_batches (product_id, received_at);
CREATE INDEX IF NOT EXISTS idx_batches_purchase_item ON product_batches (purchase_item_id);
CREATE INDEX IF NOT EXISTS idx_batches_product_available ON product_batches (product_id, qty_available);
CREATE INDEX IF NOT EXISTS idx_batches_fefo ON product_batches (product_id, expires_at, received_at);